/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Cube005: THREE.Mesh
    Cube005_1: THREE.Mesh
    Cube005_2: THREE.Mesh
  }
  materials: {
    ['Pink.002']: THREE.MeshStandardMaterial
    Pink: THREE.MeshStandardMaterial
    ['Pink.001']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/neoney.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[1.02, 0, 0.82]} rotation={[0, 0, Math.PI]} scale={[0.08, 0.05, 0.22]}>
        <mesh geometry={nodes.Cube005.geometry} material={materials['Pink.002']} />
        <mesh geometry={nodes.Cube005_1.geometry} material={materials.Pink} />
        <mesh geometry={nodes.Cube005_2.geometry} material={materials['Pink.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/neoney.glb')
